In [2]:
import sqlite3
import pandas as pd

In [4]:
conn = sqlite3.connect('bitcoin_blockchain.db')
sql_query = "SELECT * FROM blockchain LIMIT 100"
result = pd.read_sql_query(sql_query, conn)
result

,index,avgfee,avgfeerate,avgtxsize,blockhash,feerate_percentiles,height,ins,maxfee,maxfeerate,...,swtotal_weight,swtxs,time,total_out,total_size,total_weight,totalfee,txs,utxo_increase,utxo_size_inc
0,0,0,0,0,00000000839a8e6886ab5951d76f411475428afc90947e...,"[0, 0, 0, 0, 0]",1,0,0,0,...,0,0,1231469665,0,0,0,0,1,1,117
1,1,0,0,0,000000006a625f06636b8bb6ac7b960a8d03705d1ace08...,"[0, 0, 0, 0, 0]",2,0,0,0,...,0,0,1231469744,0,0,0,0,1,1,117
2,2,0,0,0,0000000082b5015589a3fdf2d4baff403e6f0be035a5d9...,"[0, 0, 0, 0, 0]",3,0,0,0,...,0,0,1231470173,0,0,0,0,1,1,117
3,3,0,0,0,000000004ebadb55ee9096c9a2f8880e09da59c0d68b1c...,"[0, 0, 0, 0, 0]",4,0,0,0,...,0,0,1231470988,0,0,0,0,1,1,117
4,4,0,0,0,000000009b7262315dbf071787ad3656097b892abffd1f...,"[0, 0, 0, 0, 0]",5,0,0,0,...,0,0,1231471428,0,0,0,0,1,1,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0,0,0,00000000c21b38cebff4901eb0b6f4265b0adea665d8b6...,"[0, 0, 0, 0, 0]",96,0,0,0,...,0,0,1231657185,0,0,0,0,1,1,117
96,96,0,0,0,000000000ecab80b1bee41b0bff9514502d7d8c62bb842...,"[0, 0, 0, 0, 0]",97,0,0,0,...,0,0,1231658068,0,0,0,0,1,1,117
97,97,0,0,0,00000000a8ed5e960dccdf309f2ee2132badcc9247755c...,"[0, 0, 0, 0, 0]",98,0,0,0,...,0,0,1231659133,0,0,0,0,1,1,117
98,98,0,0,0,00000000cd9b12643e6854cb25939b39cd7a1ad0af31a9...,"[0, 0, 0, 0, 0]",99,0,0,0,...,0,0,1231660146,0,0,0,0,1,1,117
99,99,0,0,0,000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9e...,"[0, 0, 0, 0, 0]",100,0,0,0,...,0,0,1231660825,0,0,0,0,1,1,117